name: docker
on:
  push:
    branches:
      - docker
jobs:
  buildx:
    name: buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master
      - name: Login DockerHub
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: Install docker buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      - name: Build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7 \
            -o type=registry \
            --file ./Dockerfile.1 \
            -t joshava/cloudflare-ddns-test \
            .
      - name: docker buildx imagetools inspect
        run: docker buildx imagetools inspect joshava/cloudflare-ddns-test
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
